///
/// @Generated by Mockolo
///

import APIKit
import Combine
@testable import GitHubUsers

class GitHubUsersRepositoryProtocolMock: GitHubUsersRepositoryProtocol {
    init() {}

    private(set) var fetchUsersCallCount = 0
    var fetchUsersHandler: ((Int, Int) -> (Future<[User], SessionTaskError>))?
    func fetchUsers(userCount: Int, startId: Int) -> Future<[User], SessionTaskError> {
        fetchUsersCallCount += 1
        if let fetchUsersHandler = fetchUsersHandler {
            return fetchUsersHandler(userCount, startId)
        }
        fatalError("fetchUsersHandler returns can't have a default value thus its handler must be set")
    }
}
